CREATE DATABASE Wiki IF NOT EXISTS;
USE Wiki;
/*CREATE TABLE Users IF NOT EXISTS(
`ID` INT NOT NULL AUTO_INCREMENT,
`userName` VARCHAR(50) NOT NULL,
`password` VARCHAR(50) NOT NULL,
`lastName` VARCHAR(100) NOT NULL,
`firstName` VARCHAR(100) NOT NULL,
PRIMARY KEY(`ID`)
);
CREATE TABLE Articles IF NOT EXISTS(
`title`VARCHAR(100) NOT NULL,
CONSTRAINT `owner` FOREIGN KEY(`owner`) 
REFERENCES Users(`ID`),
`text`VARCHAR(500) NOT NULL,
);---/*