CREATE DATABASE IF NOT EXISTS Wiki;
USE Wiki;
CREATE TABLE IF NOT EXISTS Users(
`ID` INT NOT NULL AUTO_INCREMENT,
`userName` VARCHAR(50) NOT NULL,
`password` VARCHAR(50) NOT NULL,
`lastName` VARCHAR(100) NOT NULL,
`firstName` VARCHAR(100) NOT NULL,
PRIMARY KEY(`ID`)
);
CREATE TABLE  IF NOT EXISTS Articles(
`title` VARCHAR(100) NOT NULL,
`owner` INT NOT NULL,
`text` VARCHAR(500) NOT NULL,
CONSTRAINT `owner` FOREIGN KEY(`owner`) 
REFERENCES Users(`ID`)
);